tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-variant": "#323633",
                "on-secondary": "#003828",
                "on-primary": "#003829",
                "surface-container-lowest": "#0b0f0d",
                "surface-container-low": "#181c1a",
                "tertiary-fixed-dim": "#9ed2ba",
                "error-container": "#93000a",
                "surface-container": "#1c201e",
                "on-error": "#690005",
                "on-tertiary-fixed": "#002116",
                "tertiary-container": "#699b86",
                "on-background": "#e0e3e0",
                "surface-tint": "#8bd5b9",
                secondary: "#9dd2bb",
                "secondary-fixed-dim": "#9dd2bb",
                "on-primary-fixed": "#002117",
                "on-primary-container": "#003023",
                "primary-fixed-dim": "#8bd5b9",
                "on-tertiary": "#003828",
                "on-secondary-fixed-variant": "#1c4f3e",
                "on-error-container": "#ffdad6",
                "inverse-surface": "#e0e3e0",
                "outline-variant": "#3f4944",
                "on-primary-fixed-variant": "#00513d",
                "primary-container": "#559e84",
                "surface-container-high": "#272b29",
                "on-secondary-container": "#90c3ad",
                "tertiary-fixed": "#baeed6",
                "primary-fixed": "#a6f2d4",
                "on-secondary-fixed": "#002116",
                surface: "#101412",
                "inverse-on-surface": "#2d312f",
                tertiary: "#9ed2ba",
                "secondary-fixed": "#b9eed6",
                "on-tertiary-fixed-variant": "#1e4f3e",
                "on-surface": "#e0e3e0",
                error: "#ffb4ab",
                background: "#101412",
                "inverse-primary": "#1b6a53",
                outline: "#89938d",
                "on-tertiary-container": "#003122",
                "surface-bright": "#363a38",
                "on-surface-variant": "#bec9c3",
                "surface-container-highest": "#323633",
                "surface-dim": "#101412",
                "secondary-container": "#1f5240",
                primary: "#8bd5b9",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                gutter: "24px",
                "section-gap-desktop": "160px",
                base: "8px",
                "section-gap-mobile": "80px",
                "container-max": "1280px",
                "margin-mobile": "20px",
            },
            fontFamily: {
                "label-md": ["JetBrains Mono", "monospace"],
                "code-sm": ["JetBrains Mono", "monospace"],
                "headline-lg": ["Outfit", "sans-serif"],
                "headline-lg-mobile": ["Outfit", "sans-serif"],
                "headline-md": ["Outfit", "sans-serif"],
                "body-lg": ["Plus Jakarta Sans", "sans-serif"],
                display: ["Outfit", "sans-serif"],
                "body-md": ["Plus Jakarta Sans", "sans-serif"],
            },
            fontSize: {
                "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
                "code-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
                "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
                "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
                "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                display: ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
            },
        },
    },
};
